"""
ChainPulse — Fixture Data
All hardcoded nodes, edges, and shipments for the supply chain graph.
"""

NODES = [
    {"id": "surat", "label": "Surat Warehouse", "type": "warehouse", "lat": 21.1702, "lng": 72.8311},
    {"id": "ahmedabad", "label": "Ahmedabad Hub", "type": "hub", "lat": 23.0225, "lng": 72.5714},
    {"id": "pune", "label": "Pune Manufacturing", "type": "warehouse", "lat": 18.5204, "lng": 73.8567},
    {"id": "mumbai_port", "label": "Mumbai Port", "type": "port", "lat": 18.9388, "lng": 72.8354},
    {"id": "nhava_sheva", "label": "Nhava Sheva Terminal", "type": "terminal", "lat": 18.9543, "lng": 72.9512},
    {"id": "chennai_port", "label": "Chennai Port", "type": "port", "lat": 13.0827, "lng": 80.2707},
    {"id": "colombo", "label": "Colombo Port", "type": "port", "lat": 6.9271, "lng": 79.8612},
    {"id": "dubai", "label": "Dubai Logistics Hub", "type": "hub", "lat": 25.2048, "lng": 55.2708},
    {"id": "singapore", "label": "Singapore Hub", "type": "hub", "lat": 1.3521, "lng": 103.8198},
    {"id": "rotterdam", "label": "Rotterdam Port", "type": "port", "lat": 51.9225, "lng": 4.4792},
]

EDGES = [
    {"source": "surat", "target": "ahmedabad", "base_time": 6, "base_cost": 8000, "base_reliability": 0.97},
    {"source": "ahmedabad", "target": "mumbai_port", "base_time": 10, "base_cost": 15000, "base_reliability": 0.95},
    {"source": "ahmedabad", "target": "pune", "base_time": 5, "base_cost": 6000, "base_reliability": 0.98},
    {"source": "mumbai_port", "target": "nhava_sheva", "base_time": 2, "base_cost": 3000, "base_reliability": 0.99},
    {"source": "nhava_sheva", "target": "colombo", "base_time": 48, "base_cost": 45000, "base_reliability": 0.93},
    {"source": "nhava_sheva", "target": "chennai_port", "base_time": 24, "base_cost": 28000, "base_reliability": 0.91},
    {"source": "chennai_port", "target": "singapore", "base_time": 72, "base_cost": 85000, "base_reliability": 0.88},
    {"source": "colombo", "target": "singapore", "base_time": 60, "base_cost": 92000, "base_reliability": 0.94},
    {"source": "singapore", "target": "rotterdam", "base_time": 240, "base_cost": 320000, "base_reliability": 0.96},
    {"source": "dubai", "target": "rotterdam", "base_time": 120, "base_cost": 180000, "base_reliability": 0.97},
    {"source": "nhava_sheva", "target": "dubai", "base_time": 96, "base_cost": 120000, "base_reliability": 0.95},
    {"source": "mumbai_port", "target": "chennai_port", "base_time": 20, "base_cost": 22000, "base_reliability": 0.90},
    {"source": "pune", "target": "mumbai_port", "base_time": 4, "base_cost": 7000, "base_reliability": 0.97},
]

SHIPMENTS = [
    # 12 shipments through Chennai Port
    {"id":"SHIP-001","origin":"surat","destination":"singapore","current_leg":("nhava_sheva","chennai_port"),
     "route":["surat","ahmedabad","mumbai_port","nhava_sheva","chennai_port","singapore"],
     "value_inr":4500000,"sla_deadline_hours":168,"criticality":"high","client_name":"Tata Electronics","status":"active"},
    {"id":"SHIP-002","origin":"ahmedabad","destination":"rotterdam","current_leg":("chennai_port","singapore"),
     "route":["ahmedabad","mumbai_port","nhava_sheva","chennai_port","singapore","rotterdam"],
     "value_inr":7200000,"sla_deadline_hours":240,"criticality":"high","client_name":"Bosch India","status":"active"},
    {"id":"SHIP-003","origin":"pune","destination":"singapore","current_leg":("mumbai_port","chennai_port"),
     "route":["pune","mumbai_port","chennai_port","singapore"],
     "value_inr":3200000,"sla_deadline_hours":144,"criticality":"high","client_name":"Samsung","status":"active"},
    {"id":"SHIP-004","origin":"surat","destination":"rotterdam","current_leg":("nhava_sheva","chennai_port"),
     "route":["surat","ahmedabad","mumbai_port","nhava_sheva","chennai_port","singapore","rotterdam"],
     "value_inr":6800000,"sla_deadline_hours":216,"criticality":"high","client_name":"L&T Manufacturing","status":"active"},
    {"id":"SHIP-005","origin":"mumbai_port","destination":"singapore","current_leg":("mumbai_port","chennai_port"),
     "route":["mumbai_port","chennai_port","singapore"],
     "value_inr":2800000,"sla_deadline_hours":120,"criticality":"medium","client_name":"Mahindra Logistics","status":"active"},
    {"id":"SHIP-006","origin":"ahmedabad","destination":"singapore","current_leg":("nhava_sheva","chennai_port"),
     "route":["ahmedabad","mumbai_port","nhava_sheva","chennai_port","singapore"],
     "value_inr":5100000,"sla_deadline_hours":192,"criticality":"high","client_name":"Tata Electronics","status":"active"},
    {"id":"SHIP-007","origin":"pune","destination":"rotterdam","current_leg":("chennai_port","singapore"),
     "route":["pune","mumbai_port","chennai_port","singapore","rotterdam"],
     "value_inr":5600000,"sla_deadline_hours":200,"criticality":"medium","client_name":"Bosch India","status":"active"},
    {"id":"SHIP-008","origin":"surat","destination":"singapore","current_leg":("mumbai_port","chennai_port"),
     "route":["surat","ahmedabad","mumbai_port","chennai_port","singapore"],
     "value_inr":3900000,"sla_deadline_hours":156,"criticality":"high","client_name":"Samsung","status":"active"},
    {"id":"SHIP-009","origin":"ahmedabad","destination":"rotterdam","current_leg":("nhava_sheva","chennai_port"),
     "route":["ahmedabad","mumbai_port","nhava_sheva","chennai_port","singapore","rotterdam"],
     "value_inr":8000000,"sla_deadline_hours":240,"criticality":"high","client_name":"L&T Manufacturing","status":"active"},
    {"id":"SHIP-010","origin":"mumbai_port","destination":"rotterdam","current_leg":("mumbai_port","chennai_port"),
     "route":["mumbai_port","chennai_port","singapore","rotterdam"],
     "value_inr":4200000,"sla_deadline_hours":180,"criticality":"medium","client_name":"Mahindra Logistics","status":"active"},
    {"id":"SHIP-011","origin":"pune","destination":"singapore","current_leg":("nhava_sheva","chennai_port"),
     "route":["pune","mumbai_port","nhava_sheva","chennai_port","singapore"],
     "value_inr":2500000,"sla_deadline_hours":132,"criticality":"medium","client_name":"Samsung","status":"active"},
    {"id":"SHIP-012","origin":"surat","destination":"rotterdam","current_leg":("chennai_port","singapore"),
     "route":["surat","ahmedabad","mumbai_port","nhava_sheva","chennai_port","singapore","rotterdam"],
     "value_inr":6200000,"sla_deadline_hours":220,"criticality":"high","client_name":"Tata Electronics","status":"active"},
    # 8 shipments NOT through Chennai Port
    {"id":"SHIP-013","origin":"nhava_sheva","destination":"singapore","current_leg":("nhava_sheva","colombo"),
     "route":["nhava_sheva","colombo","singapore"],
     "value_inr":3500000,"sla_deadline_hours":144,"criticality":"medium","client_name":"Bosch India","status":"active"},
    {"id":"SHIP-014","origin":"nhava_sheva","destination":"rotterdam","current_leg":("nhava_sheva","dubai"),
     "route":["nhava_sheva","dubai","rotterdam"],
     "value_inr":5800000,"sla_deadline_hours":216,"criticality":"low","client_name":"Mahindra Logistics","status":"active"},
    {"id":"SHIP-015","origin":"surat","destination":"pune","current_leg":("ahmedabad","pune"),
     "route":["surat","ahmedabad","pune"],
     "value_inr":900000,"sla_deadline_hours":96,"criticality":"low","client_name":"L&T Manufacturing","status":"active"},
    {"id":"SHIP-016","origin":"ahmedabad","destination":"rotterdam","current_leg":("nhava_sheva","dubai"),
     "route":["ahmedabad","mumbai_port","nhava_sheva","dubai","rotterdam"],
     "value_inr":4700000,"sla_deadline_hours":200,"criticality":"medium","client_name":"Tata Electronics","status":"active"},
    {"id":"SHIP-017","origin":"nhava_sheva","destination":"rotterdam","current_leg":("colombo","singapore"),
     "route":["nhava_sheva","colombo","singapore","rotterdam"],
     "value_inr":6100000,"sla_deadline_hours":230,"criticality":"low","client_name":"Samsung","status":"active"},
    {"id":"SHIP-018","origin":"surat","destination":"mumbai_port","current_leg":("surat","ahmedabad"),
     "route":["surat","ahmedabad","mumbai_port"],
     "value_inr":1200000,"sla_deadline_hours":96,"criticality":"low","client_name":"Bosch India","status":"active"},
    {"id":"SHIP-019","origin":"pune","destination":"dubai","current_leg":("nhava_sheva","dubai"),
     "route":["pune","mumbai_port","nhava_sheva","dubai"],
     "value_inr":3800000,"sla_deadline_hours":168,"criticality":"medium","client_name":"L&T Manufacturing","status":"active"},
    {"id":"SHIP-020","origin":"ahmedabad","destination":"colombo","current_leg":("nhava_sheva","colombo"),
     "route":["ahmedabad","mumbai_port","nhava_sheva","colombo"],
     "value_inr":2100000,"sla_deadline_hours":120,"criticality":"low","client_name":"Mahindra Logistics","status":"active"},
]

EVENT_TYPES = ["Cyclone Alert", "Port Congestion", "Labour Strike", "Customs Hold", "Equipment Failure"]
